### ISSUE TITLE
Question about the Section "Polymorphism" in Lecture 4 "C++ and computer architecture"

### ISSUE THREAD

**Issue by Naetw** [yungyuc/nsd#24]
The first paragraph says that:

> C++ detects the type of the polymorphic object in runtime, and use the type information to find the associated member function.

But I have the impression that the virtual function is implemented by the vtable mechanism and vtable is just a static array of function pointers set at compile time which doesn't need to be checked at runtime. 

As a result, I did some researches on this and I found this [article](https://www.learncpp.com/cpp-tutorial/125-the-virtual-table/) explaining the vtable mechanism and I also did an experiment on [Compiler Explorer](https://godbolt.org/z/P9efba). The experiment shows that the assembly for the function call on a virtual function is emitted in the form of taking the pointer of vtable and then just using the right offset to get the correct function pointer, which doesn't contain a check mentioned in that paragraph.

I remember that you mentioned vtable in the course this Monday, so does the "using the type information" mean using vtable? If so, I think it's a bit misleading and maybe it can be rewritten to something like:

> C++ detects the type of the polymorphic object in runtime if necessary (e.g., `dynamic_cast`), and uses the vtable to find the associated member function when we need a virtual function call.

Correct me if I'm wrong. Thanks!

**Comment by Naetw** [comment]
Oh, I just realized that vtable is just an implementation chosen by some popular compilers. It's not ruled by the standard. So, the rewritten sentence is inappropriate. I think there's no problem with the original description. Sorry for the bother.

**Comment by yungyuc** [comment]
It's not bothering.  You pointed out an important fact that the implementation of using virtual function table does not contain explicit conditional branching (jump).  However, it does not mean that the implementation "doesn't need to be checked at runtime".  Dereferencing the pointer (associated with the instance) to the static function table is runtime check.  You can verify that by comparing the assembly by instantiating `D2` and directly call the function:

```cpp
d2.function2();
```

The compiler knows which function to call without needing to dereferencing a pointer.

I agree with you that the proposed modification to include the virtual function table is not appropriate, because the standard does not require compiler or runtime library to use virtual function table, also all mainstream compilers chose that implementation.

And to your question 'so does the "using the type information" mean using vtable?'  My answer is yes.  Since using the virtual function table mandates the dereference of the function pointers, it is correct to say the implementation forces runtime check for the type.

**Comment by Naetw** [comment]
I got your point, but I still won't say that dereferencing a pointer is a check. Since I think a check contains an explicit conditional branch, I would say dereferencing a pointer is an overhead.

> And to your question 'so does the "using the type information" mean using vtable?', my answer is yes.

Agree! Since vtable is part of the type object, it's correct to say using it is using the type information.

---

Thanks for your reply! It helps clarify my understanding.
